### ISSUE TITLE
You want to keep the structure when you specify the output directory

### ISSUE THREAD

**Issue by toshiharu-irie** [stevenschobert/metalsmith-sass#13]
I have build the directory.

* /src
  * /common
    * /sass
      * common.scss
      * /ex
        * ex.scss
  * /products
    * /sass
      * index.scss

I will request

* /src
  * /common
    * /css
      * common.css
      * /ex
        * ex.css
  * /products
    * /css
      * index.css

but, it is not possible to specify the outputDir.
I want to replace the sass directory to css directory.

how do it?

**Comment by stevenschobert** [comment]
Going to go ahead and close for now, but feel free to reply back if you have more questions!
