### ISSUE TITLE
npm install metalsmith-sass failed with node v0.12

### ISSUE THREAD

**Issue by xenyou** [stevenschobert/metalsmith-sass#16]
I got ELIFECYCLE error when installing a dependency, node-sass.
Maybe it's needed to update dependent node-sass version.

My environments:
OS: Mac OS X 10.10
node: 0.12

FYI, install is done well when I switched to node 0.10.

**Comment by ubenzer** [comment]
I think it is related to this: https://github.com/sass/node-sass/issues/653 which means, node-saas needs to fixed first. :(

**Comment by xenyou** [comment]
Oh!! I had thought node-sass was already 2.0 but it's now 2.0 beta.
Okay, so I'll close it. Thanks.

**Comment by stevenschobert** [comment]
Thanks @ubenzer for pointing that out. I usually try to wait until a node-sass release is stable before upgrading it here.
