### ISSUE TITLE
node-sass 2.01 works with node 0.12, metalsmith-sass install still fails

### ISSUE THREAD

**Issue by wgregp** [stevenschobert/metalsmith-sass#18]
Looks like the underlying problem with node-sass behind
https://github.com/stevenschobert/metalsmith-sass/issues/16
has been fixed (node-sass is no longer in beta, now at 2.01), so it should be possible to update the plugin to work under node 0.12.

**Comment by stevenschobert** [comment]
Oh cool, good to know! Are there any breaking or big changes in v2 that would disrupt current users?

**Comment by wgregp** [comment]
There are a bunch of things noted with "v2" in the readme. Doesn't look like anything serious would break, but definitely worth a look. 



Greg PhillipsTwenty-seven B Stroke Six

[handheld ⇒ terse]

**Comment by farneman** [comment]
Looks like #19 would fix this. Any chance of getting an update soon?

**Comment by stevenschobert** [comment]
This is now fixed in [v0.7.0](https://github.com/sass/node-sass/releases/tag/v2.0.1), thanks to @WesleydeSouza for patching it!
