### ISSUE TITLE
scss files in subfolders do not output

### ISSUE THREAD

**Issue by hellatan** [stevenschobert/metalsmith-sass#22]
if i have this file structure:
```bash
/
- _src
-- scss
--- main.scss
--- pages
---- home.scss
```

and these settings:

```js
outputStyle: 'compressed',
outputDir: './css',
sourceMap: true,
sourceMapContents: true,
includePaths: ['./_src/scss'],
files: ['./_src/scss/**/*.scss']
```
anything under the `./_src/scss/pages` subdirectory does not get created. The process seems to try to create a `./css/home.css` file but actually never writes the file.

I'll provide more info later (just running late right now)

**Comment by stevenschobert** [comment]
Welp, that's no good! Sorry you're experiencing issues!

It might not be related, but I'm curious about a couple of your setup:

1. Why do you have `includePaths` and `files` manually specified?
2. What version of metalsmith-sass are you using?

**Comment by hellatan** [comment]
1. I think i was just mucking around with settings. Exclusively using just the `files` property (same value) yields the same result. This same issue was still happening when exclusively using the `includePaths` property as well.
2. version 1.0.0

I dug around in `lib/index.js` to do a little output and this is what I was getting in the `sass.render` callback, right before the `delete[files[filename];` functionality:

```js
filename:  scss/home.scss  :: dest:  css/home.css
filename:  scss/post.scss  :: dest:  css/post.css
filename:  scss/pages/home.scss  :: dest:  css/home.css
filename:  scss/pages/post.scss  :: dest:  css/post.css
filename:  scss/main.scss  :: dest:  css/main.css
```

I think this is actually due to the fact that I am passing in an `outputDir` option. I see that by default it is getting the correct directory. I was just hoping that I could keep my files in a `scss` directory and then move them into a `css` directory at build time instead.

I've done the following instead now:
1. changed my source files to be in a `css` directory
2. removed the `outputDir` from my passed in options.

**Comment by stevenschobert** [comment]
Ahh I see what you mean now! Yeah, setting the `outputDir` option forces *all* files to be put in the destination folder, regardless of where they came from. Let me see what I can do to make option a little more flexible!

**Comment by stevenschobert** [comment]
Hey @hellatan! Just wanted to let you know that I just pushed out [v1.1](http://github.com/stevenschobert/metalsmith-sass/releases/v1.1.0), that lets you use a function in the `outputDir` instead of just a string.

So this should do what you you're looking for

```js
Metalsmith()
  .source("src/")
  .destination("build/")
  .use(sass({
    outputDir: function(originalPath) { 
      // this will change scss/some/path to css/some/path
      return originalPath.replace("scss", "css");
    }
  }))
  .build(function () {
    done();
  });
```

**Comment by hellatan** [comment]
cool! i was thinking of doing something behind the scenes but not sure if the effort to make it super flexible would b worth the pay off.

**Comment by stevenschobert** [comment]
@hellatan What did you have in mind?

**Comment by hellatan** [comment]
@stevenschobert i think your solution along with the documentation helps out with this issue. If i can come up with a more thought out solution, I'll open up a new issue for it. Like i said, the code I was going to propose is going to need a little more time than what i have right now.

**Comment by stevenschobert** [comment]
@hellatan alrighty, sounds good, thanks!
