### ISSUE TITLE
output is a .sass file containing HTML

### ISSUE THREAD

**Issue by freder** [stevenschobert/metalsmith-sass#23]
hi,

maybe I don't fully get `metalsmith` yet, but `metalsmith-sass` is the first big problem I ran into.

with the following folder structure

```
.
├── src
│   ├── styles.sass
│   ├── index.md
│   └── posts
│       ├── ...
```

and this code:

```javascript
var vars = {
	path: {
		source: 'src',
		destination: 'build'
	}
};

Metalsmith(__dirname)
	.source(vars.path.source)
	.destination(vars.path.destination)

	.use(sass({
		// outputStyle: 'expanded',
		// outputDir: 'css',
		// sourceMap: true,
		// sourceMapContents: true,
		indentedSyntax: true
	}))

	// [...] more stuff

	.build();
```

everything is output into the specified build dir, as it should — except instead of a .css file, I get this:

```
.
├── build
│   ├── styles.sass
│   ├── ...
```

`styles.sass`:

```sass
<!DOCTYPE html><html><head><meta charset="utf-8"><title>title - title</title></head><body><h1>title</h1><time></time>body
	font-size: 12px<p><a href="/tags/[object Object],[object Object]">[object Object],[object Object]</a><br><a href="/tags/[object Object]">[object Object]</a><br><a href="/tags/[object Object]">[object Object]</a><br></p></body></html>
```

looks like a template is being applied to the sass code, but I can't figure out why. — any ideas what's going wrong here?

thanks a lot in advance.

**Comment by stevenschobert** [comment]
Hey @freder! This one is actually my fault :( metalsmith-sass didn't know how to recognize `.sass` files (since it wasn't broadly supported in libsass until recently).

But, good news! If you update to the latest release ([v1.2](http://github.com/stevenschobert/metalsmith-sass/releases/v1.2.0), I've added in support for `.sass` files.

**Comment by freder** [comment]
thanks, @stevenschobert
