### ISSUE TITLE
@functions @for loop error

### ISSUE THREAD

**Issue by karneaud** [stevenschobert/metalsmith-sass#31]
I've used the following in a previous sass file and it works

```
@function makelongshadow($color, $len) {
  $val: 0px 0px $color;
  @for $i from 1 through $len {
    $val: #{$val}, #{$i}px #{$i}px #{$color};
  }
  @return $val;
}
```

However, in trying to use it in metalsmith.json build via CLI I get

>   Metalsmith · [metalsmith-sass] Error: error parsing interpolated value

is your script unable to parse the @function?

**Comment by karneaud** [comment]
I note that if I remove the comma from

```
$val: #{$val}, #{$i}px #{$i}px #{$color};
```

it does not error. I believe this could be a parsing glitch on your part here?

**Comment by stevenschobert** [comment]
Hey @karneaud! This plugin doesn't handle any of the sass compiling directly, it just passes it through to [node-sass](https://github.com/sass/node-sass), which uses [libsass](https://github.com/sass/libsass).

You might want to check the documentation/issues for both of those. Let me know if there's anything else I can help with!

**Comment by karneaud** [comment]
@stevenschobert are you sure here because I must admit I did not have a problem using it in a previous sass project, though I must admit I was using grunt-sass environment

**Comment by stevenschobert** [comment]
It's also possible another metalsmith plugin is modifying your sass before it gets compiled. You might try temporarily removing metalsmith-sass and seeing what your sass files look like when you run a build.

**Comment by karneaud** [comment]
@stevenschobert  well I'll see but if I remove the metalsmith-sass then no sass will be compiled...I don't see how this troubleshoots my problem if you say that your plugin just feeds it off to the node-sass/ libsass

**Comment by karneaud** [comment]
@stevenschobert  with the bug found in the libsass is it that I need to update my sass? or update the metalsmith-sass?
