### ISSUE TITLE
CLI tries to compile .html files

### ISSUE THREAD

**Issue by marr** [stevenschobert/metalsmith-sass#32]
Hi,
Thank you for this plugin, looks to be a nice way to support sass in metalsmith projects.

I am experimenting and using the cli with a barebones project appears to cause an exeption:

```
Error: [metalsmith-sass] Error: Invalid CSS after "": expected 1 selector or at-rule, was "<!DOCTYPE html>" -> /Users/dmarr/src/metalsmith-project/src/setting-up-your-awesome-website/scss/styles.scss:1:1
    at Object.callback (/Users/dmarr/src/metalsmith-project/node_modules/metalsmith-sass/lib/index.js:69:23)
    at options.error (/Users/dmarr/src/metalsmith-project/node_modules/node-sass/lib/index.js:280:32)
```
This is using the command `metalsmith` within the following repo: https://github.com/marr/metalsmith-project. There is a build.js script which uses the JS api and the exception does not occur with that method. Is there something I'm missing in metalsmith.json which would cause the CLI to throw the exception above?

Thanks

**Comment by denizdogan** [comment]
I had a similar problem, but I was using the JS API all the time. What solved it for me was that I moved the `.use(sass({...}))` up earlier in the pipeline.
