### ISSUE TITLE
Sass Overwriting Autoprefixer, or vice versa

### ISSUE THREAD

**Issue by jamiewilson** [stevenschobert/metalsmith-sass#35]
I'm having trouble with processing scss and autoprefixer. If I compile sass first, autoprefixer will remove sourcemaps. If I prefix first, Metalsmith-Sass will overwrite prefixes. Any ideas?

Note: I'm not sure yet if this is a question for you or [Metalsmith-Autoprefixer](https://github.com/esundahl/metalsmith-autoprefixer). But thanks for the help!

**Comment by stevenschobert** [comment]
Hey @jamiewilson! Can you share more details about your setup?

Also, are you not seeing source maps at all, or are they just incorrect?

**Comment by jamiewilson** [comment]
Hey @stevenschobert, thanks for following up. Here is my general setup:

```js
var metalsmith = require('metalsmith');
var prefix     = require('metalsmith-autoprefixer');
var sass       = require('metalsmith-sass');

metalsmith(__dirname)
  .use(prefix())
  .use(sass({
    includePaths: ['assets/css'],
    outputDir: "css",
    outputStyle: "compressed",
    sourceMap: true,
    sourceMapContents: true
  }))
  .build();
```

Now, with this configuration, sass would get compiled with maps, but no prefixes. If I moved `prefix()` after `sass()`, I get prefixes but no sourcemaps. [My actual setup has more going on](https://github.com/jamiewilson/statt/blob/browsersync/config/metalsmith.js), but I'm pretty sure it's isolated to the order of these two.

**Comment by stevenschobert** [comment]
Heya @jamiewilson! So I think I've got my head wrapped around it now.

The problem you are running into, is that they plugin you are using for autoprefixing only works on `.css` files, and not the `.scss` files directly. (You can check that by looking at the [`lib/index.js`](https://github.com/esundahl/metalsmith-autoprefixer/blob/81db02455461a2783fe28aa3ec844d160a420e30/lib/index.js#L10) file)

That probably works well for just about everyone, but it limits _your_ particular use case in the following ways:

1. You have to compile the sass before the autoprefixer can run (not really a big deal on its own)
2. You source maps become invalidated if you modify the `.css` files (like by running them through a autoprefixer)

The good news is that there are flavors of the _postcss_ projects that know how to parse the `.scss` files directly, which would allow you to run autoprefixer _before_ the sass compiles, which will in turn allow your source maps to be correct.

To help you out, I built a quick demo project that does exactly that. Feel free to look it over and copy/modify to suit your needs. Hope it helps!
**&rarr; https://github.com/stevenschobert/metalsmith-sass-autoprefixer-example**

**Comment by jamiewilson** [comment]
Wow. This is super helpful. Thank you so much for doing this!
