### ISSUE TITLE
Specify input in Metalsmith's JS api

### ISSUE THREAD

**Issue by diroru** [stevenschobert/metalsmith-sass#37]
Hello,
thanks for the great plugin!

I apologise if my question comes from my ignorance, but i haven't been able to specify an input file name for the »main« `.scss` file using metalsmith's _javascript api_. Specifically, i would like to keep my `source` and `styles` folders at the same level (and not have to put the former under the latter). Here is a snippet from my `build.js`: 

```
.use(sass({
    file: 'styles/bootstrap/scss/bootstrap.scss',
    outputDir: 'css/',
    sourceMap: true,
    sourceMapContents: true
}))
```

I am asking this because i have the impression that the `methalsmith.json` supports it and it is also mentioned in the `node-sass` docs.

Thanks a lot in advance for any clarification on the matter!

Cheers,
dimitar

**Comment by stevenschobert** [comment]
Hey @diroru! Mind if I ask why you are trying to specify a single filename? Or what output are trying to get?

Generally speaking, the metalsmith mindset is to apply transformations across all or a subset of your files. This is why metalsmith-sass automatically compiles anything with a `.scss` or `.css` extension.

**Comment by diroru** [comment]
Hey @stevenschobert, thanks a lot for your reply!

I would like to compile `bootstrap`, which has a single file entry point, as far as i have understood. But apart from that, i would like to at least be able to specify the root for the sass compilation. I have the impression that this ability could remedy some of the other open issues. Also, it occurs to me, this (the `includePaths` option) is possible via metalsmith's CLI (using `metalsmith.json`).

To reiterate it, it boils down to being able to set a different `source` directory for metalsmith and sass. But then again, as you were kind enough to point it out, this might be contrary to the _metalsmith philosophy_ (the study of which i have just taken up).

It is not a nuisance, was just wondering if this way of functioning was intentional.

**Comment by stevenschobert** [comment]
Thanks for the info! So what does your project folder structure look like?

**Comment by diroru** [comment]
Thanks for your reply. An ideal setup would be something like this:

```
project_root
├-- content
├-- layouts
├-- styles (here live the scss files)
├-- …
```
Now i realize that the following would also be possible with the current functionality of `metalsmith-sass` and is probably a fine solution:

```
project_root
├-- src
     ├-- content
     ├-- layouts
     ├-- styles
     ├-- …
```
Actually, it's more of a gut feeling that it might be beneficial to be able to set a custom, but underlying root  for the sass compiler. Also, your project description says 

> See node-sass for a complete list of supported options.

that's why I thought that the option `file` or `includePaths` might be used. But i don't want to be a nuisance and i have the impression that this discussion is getting academic (and i am the less literate party), so feel free to close this issue at your leisure. Thanks for your patience and interest so far!

Cheers,
dimitar

**Comment by mdotasia** [comment]
Is there an update on this issue? I'm using the same folder structure as @diroru above, no src directory but content, layouts, partials and styles.

**Comment by stevenschobert** [comment]
@mdotasia I don't quite understand why you wouldn't have a single source directory? Metalsmith operates by being given a single directory and running all of its files through a series of plugins, basically like a pipe. Without the source directory how are you telling metalsmith what to process?

**Comment by mdotasia** [comment]
@stevenschobert Actually this issue https://github.com/stevenschobert/metalsmith-sass/issues/4 and your comments about multiple build pipelines were the missing piece for me to grasp that @diroru's second folder structure makes a lot of sense. I have now one build pipeline for content with source `src/content` and another build pipeline for Sass with source `src/styles`. That looks like a clean separation of concerns.

**Comment by stevenschobert** [comment]
@mdotasia ahh I had forgotten about that thread! yep you can definitely do multiple pipelines like that. Glad it was helpful.
