### ISSUE TITLE
metalsmith-sass does not compile

### ISSUE THREAD

**Issue by flachware** [stevenschobert/metalsmith-sass#41]
Hi,

I use `metalsmith-sass` together with `metalsmith-watch` for a very simple static site generator.

When I start the server all Sass files are compiled correctly. However, this is not the case once the server is running (watching): changes to a Sass partial (e.g. `_variables.scss`), that is included with `@import` into `main.scss` do not lead to a compilation of `main.scss` – this means that the stylesheets effectively are not updated.

That’s what I get:
```
[metalsmith-watch] - Updating 1 file...
[metalsmith-watch] ✔︎ 0 file reloaded
```

I can reproduce this issue on several machines with OS X/macOS (including v10.12.4) and all node versions (including v6.5.0). I use `metalsmith@2.3.0`, `metalsmith-watch@1.0.3` and `metalsmith-sass@1.4.0`.

Any help would be highly appreciated!

**Comment by awei01** [comment]
Sounds like an issue with your `metalsmith-watch` config. If you send the folder structure and `metalsmith` script, it'd be easier to debug. Or, better yet, a link to your repo.

**Comment by flachware** [comment]
Thank you for your offer to help, but I already moved on to npm scripts – closing (sorry for my late response).
