### ISSUE TITLE
all scss files are processed, even the not used ones

### ISSUE THREAD

**Issue by oupala** [stevenschobert/metalsmith-sass#42]
I'm having a strange behaviour with metalsmith-sass: all scss files are processed, even the not used ones.

I'm using the following configuration:

```js
    .use(sass({
      file: './src/scss/app.scss',
      includePaths : [
        './node_modules/boostrap/scss',
        './src/vendor/highlight.js/styles/' // all highlight.js scss files
      ],
      outputDir: 'css/', // this changes the output dir to "build/css/" instead of "build/scss/"
      outputStyle: 'compressed',
      sourceMap: true,
      sourceMapContents: true // this will embed all the sass contents in sourcemaps
    }))
```

My `./src/scss/app.scss` file is importing the needed scss files.

I'm expecting a unique file to be built into the `css` directory: `app.css`.

I'm having this `app.css` compiled file. But I'm also having all highlight.js sccs files compiled into css. I do not need these files as I'm importing only one theme and this theme file is already included into my `app.css` file.

I found an issue about that problem: #22 (even if that issue is the opposite problem) and I find that the [solution is a bit strange](/stevenschobert/metalsmith-sass/issues/22#issuecomment-109620519):

> Ahh I see what you mean now! Yeah, setting the outputDir option forces all files to be put in the destination folder, regardless of where they came from. Let me see what I can do to make option a little more flexible!

> Just wanted to let you know that I just pushed out v1.1, that lets you use a function in the outputDir instead of just a string.

Why do I have to use a function to avoid having all the scss file compiled as I'm using a `file` parameter to tell sass to process only this file (and imported scss files).

By the way, the `file` parameter is not documented. Is it normal?

In the documentation, I don't the link between this `file` parameter, the `outputDir` function and the way sass processes files.

If one can explain that to me, and possibly clarify the documentation, it would be great!

**Comment by stevenschobert** [comment]
Hey @oupala! The `file` parameter isn't supported in metalsmith-sass. Instead, metalsmith-sass will automatically process _all_ files ending in `.scss`.

You can instruct metalsmith-sass to ignore files you don't need, by prefixing the filename with an `_` underscore (example: `_buttons.scss`).

**Comment by oupala** [comment]
It could be a good idea to tell which option is supported or not. The [documentation tells](https://github.com/stevenschobert/metalsmith-sass#options):

> See node-sass for a complete list of supported options.

So it hard to tell which option is supported or not.

In my case, I have only one scss file in my `scss` directory. But this scss file is importing files from other directories. I don't want **all** files from these directories to be compiled by sass, but only those who are use (and imported) by `scss/app.scss`.

In the end, I only want one css file to be generated.

And I can't rename all files with an `_` (underscore) as these files are dependencies (boostrap and highlight.js) and I cannot change them as they are included at build time.

How should I use metalsmith-sass in my case, why is the `file` parameter is not supported?

**Comment by stevenschobert** [comment]
> So it hard to tell which option is supported or not.

Yeah, I agree, the docs should be more clear about which options work. In general, all of the options work except for options that deal with telling node-sass which files to process -- that function is controlled by metalsmith-sass. (Which is because metalsmith-sass is just a thin wrapper around node-sass, and passes the file data + extra options to it) 

> And I can't rename all files with an _ (underscore) as these files are dependencies (boostrap and highlight.js) and I cannot change them as they are included at build time.

In that case, I recommend using a plugin like [metalsmith-ignore](https://github.com/segmentio/metalsmith-ignore) to exclude any extra compiled `scss` files from your build.

> [...] How should I use metalsmith-sass in my case, why is the file parameter is not supported?

The file option can't be directly supported, because "real files" don't exist during the build process. Everything is memory buffers by metalsmith, as it runs through the list of plugins, and doesn't create the final files on disk until the very end. So if you were to just pass a `file` to node-sass, then that file couldn't include any changes metalsmith made to file before metalsmith-sass runs.

Ultimately, I think metalsmith-sass needs a `filter` option (like other plugins have), so that it could support "targeting" specific files, instead of grabbing all of them. I just don't have time to add that function right now.

**Comment by oupala** [comment]
Thanks for the answer. I understand that metalsmith is in charge of managing streams and buffers of files, which is not the job of metalsmith-sass (even if a **filter** option would be welcomed).

I will think about using **metalsmith-ignore**.

But in the end, what files are processed by metalsmith-sass, all files ending with `.scss` and `.sass`? As you can see in my first post, my only scss file is never included in the `includePaths` but it is processed. And the `boostrap/scss` file are processed although they are not in the source directory of metalsmith. This is why I'm having difficulties to matter which files will be processed by metalsmith. If you can give a bit more explanations about that, I'd be glad!

**Comment by stevenschobert** [comment]
Yes, any `.scss` or `.sass` file, that is in the metalsmith source directory, and does not begin with an underscore `_`, will get processed.

The main plugin function loops over each file, calling `compile` ([code](https://github.com/stevenschobert/metalsmith-sass/blob/292f1180b6fde7e1720d1375a284c5338dc23e04/lib/index.js#L119)), and in the compile function, it calls `isAnySassFile` ([code](https://github.com/stevenschobert/metalsmith-sass/blob/292f1180b6fde7e1720d1375a284c5338dc23e04/lib/index.js#L60)), which uses the following regex ([code](https://github.com/stevenschobert/metalsmith-sass/blob/292f1180b6fde7e1720d1375a284c5338dc23e04/lib/index.js#L26-L28)):

```js
(/^[^_.].*\.s[ac]ss/).test(path.basename(filename));
```

---

> And the `boostrap/scss` file are processed although they are not in the source directory of metalsmith

If that directory isn't in the metalsmith source directory, it shouldn't be processed explicitly by metalsmith-sass.

**Comment by oupala** [comment]
Thanks @stevenschobert for all these informations.
