### ISSUE TITLE
Absolute content paths are not supported correctly

### ISSUE THREAD

**Issue by RetrocadeNet** [stevenschobert/metalsmith-sass#44]
If you attempt to use _metalsmith-sass_ with content path being absolute instead of relative it'll concat the paths and result in something akin to `C:\Projects\MetalsmithProject\C:\Projects\MetalmisthProject\Content` which will break any and all imports.

A solution is to just use `metalsmith._src`/`metalsmith._source` as-is if it is detected to be absolute.

**Comment by stevenschobert** [comment]
Oh! Thanks for the catch, and pull-request! Super helpful.

I'd like to get a test case around this. To clarify, this is when you set the Metalsmith source directory to an absolute path?

```js
Metalsmith(__dirname)
  .source("C:\Projects\MyProject")
  // ...
```

**Comment by RetrocadeNet** [comment]
@stevenschobert Yep, exactly that.

I've missed the fact there are tests written, I've added a case to cover this issue to my PR :)

**Comment by stevenschobert** [comment]
Awesome, thanks @RetrocadeNet! I'll try to get this merged in and released soon! 🍻

**Comment by RetrocadeNet** [comment]
Sweet, now that #45 is merged I guess it's safe to close this task :)
