### ISSUE TITLE
Prefixing

### ISSUE THREAD

**Issue by HarryFrancis** [stevenschobert/metalsmith-sass#46]
Hello,

I was just wondering how I would go about auto-prefixing my sass on compile?

Is there a built in method or another node module that is compatible with this one?

Thanks, Harry.

**Comment by stevenschobert** [comment]
Hey @HarryFrancis!

Issue #35 might help you, it’s a couple years old, but should still be relevant.

There is also an example project I put together around that time here: https://github.com/stevenschobert/metalsmith-sass-autoprefixer-example

There is also an autoprefixer plugin for metalsmith here: https://github.com/esundahl/metalsmith-autoprefixer
