### ISSUE TITLE
Importing bulma results in an error

### ISSUE THREAD

**Issue by gabriel-sevecek** [stevenschobert/metalsmith-sass#48]
Importing bulma with:
`
@import "bulma/sass/utilities/_all.sass"
`

Results in an error:
`
Error: media query expression must begin with '('
`

Compiling my scss with sass cli tool works fine. Am I doing something wrong?

**Comment by gabriel-sevecek** [comment]
Nevermind, I was missin semicolon :/

**Comment by stevenschobert** [comment]
@gabriel-sevecek No worries, glad you got it working 👍
