### ISSUE TITLE
Node 12+ is Unsupported

### ISSUE THREAD

**Issue by emmercm** [stevenschobert/metalsmith-sass#49]
`metalsmith-sass` uses `node-sass": "^4.11.0`:

https://github.com/stevenschobert/metalsmith-sass/blob/dc23109f6513c9260ce9c365667884ee493a88cf/package.json#L32

But 4.12+ is required for Node 12: https://github.com/sass/node-sass/blob/fbc9ff5abc72d9bc22a3b0bc9fa902fc46c980f7/README.md

This wasn't a problem for me until the active Node LTS changed from v10 to v12 on Oct 21: https://nodejs.org/en/about/releases/

**Comment by nickcolley** [comment]
@stevenschobert I would be willing to do a pull request for this, could you let me know if you've got time to review and publish a new version? OK if you do not but will help me figure out what to do next (e.g. fork, vendor etc).

**Comment by stevenschobert** [comment]
Hey @nickcolley! Yes, I'd very much appreciate a pull request -- and will be happy to review it and release a new version.

Sorry, I don't keep up with the changes in node-sass very well, but I appreciate the help 😄

**Comment by stevenschobert** [comment]
@emmercm Sorry for not replying to your original comment! Luckily it sounds like @nickcolley is going to help us with a pull request to get this updated!

**Comment by nickcolley** [comment]
@stevenschobert I've opened a pull request here: https://github.com/stevenschobert/metalsmith-sass/pull/55 let me know if I can help anymore, thank you for taking the time to maintain this package.

**Comment by stevenschobert** [comment]
@nickcolley Thank you 1000x times for the PR! 🎉 

I've published [v1.7.0](https://github.com/stevenschobert/metalsmith-sass/releases/tag/v1.7.0) to NPM. Please try it out and let me know if there are any issues!

**Comment by emmercm** [comment]
That was awesome, thank you both!

**Comment by nickcolley** [comment]
@stevenschobert thanks mate, appreciate you taking the time to do that :+1:
